version: '3.8'

services:
    app:
        image: course-recommendation-frontend
        build:
            dockerfile: dockerfiles/Dockerfile.dev
            context: .
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run dev
